### PR TITLE
Remove unused grunt packages

### PR DESCRIPTION
**Pull request by gaand**
For jscs and jshint

### CODE REVIEW

**Comment by payne-chris-r** [comment]
You're changing this to just console.log instead of starting (what is now) the `example.js` script? Do we need to change `grunt/nodemon` to this?
```diff
  "server": {
-    "script": "bin/index.js"
+    "script": "bin/example.js"
  }
```
???

**Comment by payne-chris-r** [comment]
I know this is something we raaaaarely do, just wanted to make sure this was the change you expected. I've just tried it, and it works, it just isn't using any of the example code, and I'm not sure if that was your intent or not.

**Comment by gaand** [comment]
That was my intent.  The example code runs if you run `bin/example.js`.  The snippet I put on the wiki leave all the example code out.  If I left the code in `bin/index.js` then we'd have to keep `lib/example.js`.

`bin/example.js` probably gets removed once we set up test watching (almost ready).

**Comment by payne-chris-r** [comment]
Awesome. Thanks for the explanation.

**Pull request merged**
